version: 2.1
jobs:
  build:
    docker:
      - image: membraneframeworklabs/docker_membrane:latest
    environment:
      MIX_ENV: test

    steps:
      - checkout
      - run: |
          mix deps.get
          mix deps.compile --all
          mix format --check-formatted
          mix test
