version: 2.1
orbs:
  elixir: membraneframework/elixir@1

executors:
  software_rendering_executor:
    docker:
      - image: membraneframeworklabs/docker_membrane:opengl-experimental2

jobs:
  rust_lint:
    executor: 
      name: elixir/docker_membrane
      mix_env: test

    steps:
      - checkout
      - run:
          name: Rust lint
          command: |
            for path in native/*
            do
              cargo fmt --manifest-path $path/Cargo.toml -- --check
              cargo clippy --manifest-path $path/Cargo.toml -- -D warnings
            done

  rust_tests:
    executor: 
      name: elixir/docker_membrane
      mix_env: test

    steps:
      - checkout
      - run:
          name: Rust tests
          command: |
            for path in native/*
            do
              cargo test --manifest-path $path/Cargo.toml
            done

  elixir_test_with_software_rendering:
    executor: 
      name: software_rendering_executor

    steps:
      - run:
          command: echo "ABCDEFG"
          name: Ensure commands are executed

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test
      - elixir_test_with_software_rendering
      - elixir/lint
      - rust_lint
      - rust_tests
