version: 2.1
orbs:
  elixir: membraneframework/elixir@1

jobs:
  rust_lint:
    executor: 
      name: elixir/docker_membrane
      mix_env: test

    steps:
      - checkout
      - run:
          name: Rust lint
          command: |
              cargo fmt --all --manifest-path native/Cargo.toml -- --check
              cargo clippy --workspace --manifest-path native/Cargo.toml -- -D warnings

  rust_tests:
    executor: 
      name: elixir/docker_membrane
      mix_env: test

    steps:
      - checkout
      - run:
          name: Rust tests
          command: |
              cargo test --workspace --manifest-path native/Cargo.toml

workflows:
  build:
    jobs:
      - elixir/build_test:
          filters: &filters
            tags:
              only: /v.*/
      - elixir/test:
          filters:
            <<: *filters
      - elixir/lint:
          filters:
            <<: *filters
      - rust_lint:
          filters:
            <<: *filters
      - rust_tests:
          filters:
            <<: *filters
      - elixir/hex_publish:
          requires:
            - elixir/build_test
            - elixir/test
            - elixir/lint
            - rust_lint
            - rust_tests
          context:
            - Deployment
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
