version: 2.1
orbs:
  elixir: membraneframework/elixir@1

jobs:
  rust_lint:
    executor: 
      name: elixir/docker_membrane
      mix_env: test

    steps:
      - checkout
      - run:
          name: Rust lint
          command: |
            for path in native/*
            do
              cargo fmt --manifest-path $path/Cargo.toml -- --check
              cargo clippy --manifest-path $path/Cargo.toml -- -D warnings
            done

  rust_tests:
    executor: 
      name: elixir/docker_membrane
      mix_env: test

    steps:
      - checkout
      - run:
          name: Rust tests
          command: |
            for path in native/*
            do
              cargo test --manifest-path $path/Cargo.toml
            done

  elixir_test_with_software_rendering:
    docker:
      - image: membraneframeworklabs/docker_membrane:opengl-experimental

    steps:
      steps:
      - checkout
      - setup_remote_docker
      - elixir/get_mix_deps
      - elixir/use_build_cache:
          env: test
      - run:
          command: mix deps.compile
          name: Ensure native deps are compiled
      - run:
          command: mix test --warnings-as-errors
          name: Run all tests

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test
      - elixir_test_with_software_rendering
      - elixir/lint
      - rust_lint
      - rust_tests
