[package]
name = "membrane_videocompositor_wgpu"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "membrane_videocompositor_wgpu"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.26.0"
