[package]
name = "membrane_video_compositor_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustler = "0.28.0"
thiserror = "1.0.40"
wgpu = "0.14.2"
